!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supply Chain Logistics Management System</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

<div class="login-box">
    <h2>Supply Chain Logistics Management System</h2>

    <form onsubmit="return validateLogin()">

        <label>Username</label>
        <input type="text" id="username" placeholder="Enter Username">

        <label>Password</label>
        <input type="password" id="password" placeholder="Enter Password">

        <button type="submit">Login</button>

    </form>

</div>

<script src="js/script.js"></script>

</body>
</html>
